### ISSUE TITLE
Refactor the process_nclimdiv.py code to use object-oriented approach, eliminate globals

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#14]
Refactor the process_nclimdiv.py code to use object-oriented approach, using process_nclimgrid.py as an example. Eliminates globals other than a single shared file lock.

**Comment by monocongo** [comment]
Currently getting the following error on a Windows machine, running with single CPU:

2017-12-15  12:54:04 INFO Start time:    2017-12-15 12:54:04.296393
2017-12-15  12:54:09 INFO Processing indices for division 101
2017-12-15  12:54:09 INFO 	Computing PET for division 101
2017-12-15  12:54:10 INFO 	Computing PDSI for division 101
2017-12-15  12:54:26 INFO 	Computing SPI/SPEI/PNP at 1-month scale for division 101
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 429, in _handle_results
    task = get()
  File "C:\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'loc'


Code confirmed to work as expected with month-scaled indices (SPI, SPEI, and PNP) disabled.

**Comment by monocongo** [comment]
Appears to work now with the latest commit on issue_14 branch, will merge to develop branch.
