### ISSUE TITLE
SPI/SPEI error using example input data

### ISSUE THREAD

**Issue by s-m-t-c** [monocongo/climate_indices#171]
I installed climate_indices using the instructions here: https://climate-indices.readthedocs.io/en/latest/
and successfully passed all the tests. 

Using the example input files and code provided in the above link I can calculate the PET and Palmers monthly correctly but the SPI and SPEI examples produced the below error. If re-run, each example consistently produces this error at the same latitude index. 

Please let me know if you need anymore information.

~~~~
python process_grid.py --index spei --periodicity monthly --netcdf_precip /climate_indices/example_inputs/nclimgrid_lowres_prcp.nc --var_name_precip  prcp --netcdf_pet /climate_indices/example_inputs/nclimgrid_lowres_pet.nc --var_name_pet pet --output_file_base /nclimgrid_lowres --scales 9 18 --calibration_start_year 1951 --calibration_end_year 2010
2018-06-28  16:16:38 INFO Start time:    2018-06-28 16:16:38.862509
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 0
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 6
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 4
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 12
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 2
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 10
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 8
2018-06-28  16:16:39 INFO Computing 9-month SPEI for latitude index 14
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/g/data/u46/users/sc0554/anaconda3/envs/indices_repo/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/g/data/u46/users/sc0554/anaconda3/envs/indices_repo/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/g/data/u46/users/sc0554/anaconda3/envs/indices_repo/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/g/data/u46/users/sc0554/anaconda3/envs/indices_repo/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'loc'

2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 16
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 18
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 20
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 22
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 24
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 26
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 28
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 1
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 30
2018-06-28  16:16:40 INFO Computing 9-month SPEI for latitude index 32
^CProcess ForkPoolWorker-5:
Process ForkPoolWorker-2:
Process ForkPoolWorker-6:
Process ForkPoolWorker-1:
Process ForkPoolWorker-8:
Process ForkPoolWorker-3:
Process ForkPoolWorker-4:
Process ForkPoolWorker-7:
~~~~

Thanks in advance!

**Desktop:**
~~~~
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final
~~~~

Extra info:

Trying to use this library to calculate SPEI over Cambodia.

**Comment by monocongo** [comment]
Thanks for bringing this to my attention.

I may have isolated this as an issue with Numba's Just-in-Time compilation, in that when I run the above with Numba disabled, i.e. after issuing the command `$ export NUMBA_DISABLE_JIT=1`, then the SPEI processing successfully runs to completion. 

I performed this test on a laptop PC running Windows 7 Professional using a Cygwin shell.

Please try again after disabling the Numba Just-in-Time compilation, i.e. first execute this command: 

`$ export NUMBA_DISABLE_JIT=1` 

If this fixes things for you as well then we should investigate further as to what's causing the issue with Numba's JIT, as Numba is quite useful for increasing the performance of this code.

**Comment by s-m-t-c** [comment]
After disabling the Numba JIT I can successfully run the SPI and SPEI functions of climate_indices with the provided example data. I have checked the outputs with ncview (after transformation to time lat lon) and they look as expected. This explains why it can pass all the tests but still fail on an example.

Thanks for your help, these examples don't take an unreasonable amount of time without Numba but it would be useful to fix.

**Comment by monocongo** [comment]
The code has been updated whereby I've removed some Numba JIT annotations where it was causing problems, but everywhere else Numba JIT is still in play in order to leverage the performance boost it provides. The cause of this issue hasn't yet been discovered or rectified, but the immediate issue itself has been remedied, so closing for now.
