### ISSUE TITLE
Processing script for US climate divisions needs update and example input files

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#182]
The `scripts/process_divisions.py` script is out-of-date and should be updated to work on US climate division files.

- [x] Update `scripts/process_divisions.py` to correctly use the API provided by the `indices.py` module
- [x] Add example US climate division files into the `example_inputs` directory
- [ ] Update the command line options to match with those of the `process_grid.py` script
- [ ] Update documentation to describe usage for US climate divisions

**Comment by monocongo** [comment]
A user has experienced the following errors (the impetus for this issue):

```
2018-09-07  15:19:37 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "process_divisions.py", line 278, in _compute_and_write_division
    spei_gamma = indices.spei_gamma(months,
AttributeError: module 'climate_indices.indices' has no attribute 'spei_gamma'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_divisions.py", line 634, in <module>
    divisions=args.divisions)
  File "process_divisions.py", line 562, in process_divisions
    divisions_processor.run()
  File "process_divisions.py", line 352, in run
    result.get()
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: module 'climate_indices.indices' has no attribute 'spei_gamma'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "process_divisions.py", line 278, in _compute_and_write_division
    spei_gamma = indices.spei_gamma(months,
AttributeError: module 'climate_indices.indices' has no attribute 'spei_gamma'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_divisions.py", line 634, in <module>
    divisions=args.divisions)
  File "process_divisions.py", line 562, in process_divisions
    divisions_processor.run()
  File "process_divisions.py", line 352, in run
    result.get()
  File "/home/acourtright/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: module 'climate_indices.indices' has no attribute 'spei_gamma'
```

**Comment by monocongo** [comment]
Related to #187
