### ISSUE TITLE
Error computing SPI from GPCC precipitation data

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#261]
A user has reported an issue with calculating SPI using a GPCC precipitation dataset as input. It appears to be related to the format of the NetCDF itself, or the way NCO is behaving on Windows, but those are preliminary guesses based on an initial look at the stack trace. Screenshot attached.

![climate_indices_error_mario](https://user-images.githubusercontent.com/1328158/51913769-483c5400-23a5-11e9-8a49-c43b3d227a6b.png)

**Comment by monocongo** [comment]
I've downloaded the [GPCC dataset](ftp://ftp.dwd.de/pub/data/gpcc/full_data_2018/full_data_monthly_v2018_25.nc.gz) being used, and I do not get the reported error. My testing has been performed on Linux and this user is on Windows, so I'll need to test on Windows to see what's happening there.

However, another issue has been revealed with the L-Moments related code (used with Pearson Type III fittings):

```
/home/james/miniconda3/envs/climate/bin/python /home/james/git/climate_indices/scripts/process_grid.py --index spi --periodicity monthly --scales 1 2 3 --netcdf_precip /home/james/data/gpcc/full_data_monthly_v2018_25_nan_fills.nc --var_name_precip precip --output_file_base /home/james/data/gpcc/gpcc --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing single
2019-01-29  10:06:42 INFO Start time:    2019-01-29 10:06:42.351598
2019-01-29  10:06:48 INFO Computing 1-month SPI/Pearson
2019-01-29  10:06:57 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/climate/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/james/miniconda3/envs/climate/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/james/git/climate_indices/scripts/process_grid.py", line 1071, in _apply_along_axis
    computed_array = np.apply_along_axis(func1d, axis=2, arr=sub_array, parameters=args)
  File "/home/james/miniconda3/envs/climate/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 380, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "/home/james/git/climate_indices/scripts/process_grid.py", line 864, in _spi
    periodicity=parameters["periodicity"],
  File "/home/james/git/climate_indices/climate_indices/indices.py", line 120, in spi
    periodicity,
  File "/home/james/git/climate_indices/climate_indices/compute.py", line 353, in transform_fitted_pearson
    values[calibration_begin_index:calibration_end_index, :]
  File "/home/james/git/climate_indices/climate_indices/compute.py", line 213, in _pearson3_fitting_values
    params = distr.pe3.lmom_fit(time_step_values)
  File "/home/james/miniconda3/envs/climate/lib/python3.6/site-packages/lmoments3-1.0.4+4.gfcbc2e9-py3.6.egg/lmoments3/distr.py", line 65, in lmom_fit
    return self._lmom_fit(lmom_ratios)
  File "/home/james/miniconda3/envs/climate/lib/python3.6/site-packages/lmoments3-1.0.4+4.gfcbc2e9-py3.6.egg/lmoments3/distr.py", line 1277, in _lmom_fit
    raise ValueError("L-Moments invalid")
ValueError: L-Moments invalid
"""

Process finished with exit code 1
```

The above appears to be the same problem we're seeing in issue #251.

**Comment by monocongo** [comment]
The reporting user has resolved the original problem, now following up on issue #251 which was not an issue for this user on Windows.
