### ISSUE TITLE
Dimensions validation fails for AWC input (2-D is OK but expecting only 3-D)

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#294]
When the processing script is used for calculating the Palmers and is in the part where it validates the dimensions of input files it croaks when validating an available water capacity (AWC) input file if the time dimension is missing, which is normal for an AWC dataset since the data is not a timeseries (and if the time dimension is present it has a size of one). See below for the error trace.

We can fix this by looking for only ['lat, 'lon'] (or only ['division'] for US Climate Divisions input) as the dimensions for an input AWC dataset within the `__main__._validate_args` function.

```
$ process_climate_indices --index palmers --periodicity monthly --netcdf_precip  /c/home/git/example_climate_indices/example/input/nclimgrid_lowres_prcp.nc --var _name_precip prcp --netcdf_pet /c/home/git/example_climate_indices/example/input /nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc /c/home/git/example_cli mate_indices/example/input/nclimgrid_lowres_soil.nc --var_name_awc awc --output_ file_base /c/home/data/test/nclimgrid_lowres --calibration_start_year 1951 --cal ibration_end_year 2010 --multiprocessing all
2019-03-21  16:36:18 INFO Start time:    2019-03-21 16:36:18.870804
2019-03-21  16:36:18 ERROR Invalid dimensions of the AWC variable: ('lat', 'lon' )(expected names and order: [('lat', 'lon', 'time'), ('time', 'lat', 'lon')]
2019-03-21  16:36:18 ERROR Failed to complete
Traceback (most recent call last):
File "c:\home\miniconda\envs\palmers\lib\site-packages\climate_indices\__main_ _.py", line 1631, in main                                                            input_type = _validate_args(arguments)
File "c:\home\miniconda\envs\palmers\lib\site-packages\climate_indices\__main_ _.py", line 342, in _validate_args                                                   raise ValueError(msg)                                                        ValueError: Invalid dimensions of the AWC variable: ('lat', 'lon')(expected name s and order: [('lat', 'lon', 'time'), ('time', 'lat', 'lon')]                    Traceback (most recent call last):
File "c:\home\miniconda\envs\palmers\lib\runpy.py", line 193, in _run_module_a s_main                                                                               "__main__", mod_spec)                                                          File "c:\home\miniconda\envs\palmers\lib\runpy.py", line 85, in _run_code          exec(code, run_globals)                                                        File "C:\home\miniconda\envs\palmers\Scripts\process_climate_indices.exe\__mai n__.py", line 9, in                                                        File "c:\home\miniconda\envs\palmers\lib\site-packages\climate_indices\__main_ _.py", line 1631, in main                                                            input_type = _validate_args(arguments)                                         File "c:\home\miniconda\envs\palmers\lib\site-packages\climate_indices\__main_ _.py", line 342, in _validate_args                                                   raise ValueError(msg)
ValueError: Invalid dimensions of the AWC variable: ('lat', 'lon')(expected name s and order: [('lat', 'lon', 'time'), ('time', 'lat', 'lon')]                    (palmers)
```

**Comment by monocongo** [comment]
Resolved by PR #295
