### ISSUE TITLE
Palmers (PDSI): IndexError: list index out of range

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#298]
There appears to be an issue with the Palmers code in special circumstances where the Z-sum is being computed for wet conditions, in that a largest reasonable sum value may not exist and causes an out of range index value when finding the highest reasonable value within `palmer._z_sum`:

```
Traceback (most recent call last):
  File "/home/james/miniconda3/envs/citest/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/james/miniconda3/envs/citest/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/__main__.py", line 1473, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/__main__.py", line 1146, in _palmers
    calibration_end_year=parameters["calibration_end_year"],
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/palmer.py", line 1648, in _highest_reasonable_value
    sum_at_reasonable_percentile = summed_values[reasonable_percentile_index]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/james/miniconda3/envs/citest/bin/process_climate_indices", line 10, in <module>
    sys.exit(main())
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/__main__.py", line 1809, in main
    _compute_write_index(kwrgs)
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/__main__.py", line 856, in _compute_write_index
    args=args,
  File "/home/james/miniconda3/envs/citest/lib/python3.7/site-packages/climate_indices/__main__.py", line 1300, in _parallel_process
    pool.map(_apply_along_axis_palmers, chunk_params)
  File "/home/james/miniconda3/envs/citest/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/james/miniconda3/envs/citest/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: list index out of range
```

The fix for this *seems* to be to have the highest reasonable value default to 0.0 in the case where no Z-sum values are available. We'll add this fix and examine the results as an initial validation.

**Comment by monocongo** [comment]
This appears to have been resolved by PR #299
