### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by wsor330** [monocongo/climate_indices#314]
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**
Not exactly sure what the error means but i have 2-Dimensional Data, of shape, (time,stations) and it does not work with SPI.
```
$ process_climate_indices --index spi  --periodicity daily --netcdf_precip /data/Precip_1910-2018_homomod.nc --var_name_precip prcp --output_file_base /data/Precip_1910-2018_homomod --scales 30 --calibration_start_year 1910 --calibration_end_year 2018 --multiprocessing all
```
Code above produces the following errors;
```
2019-05-27  14:05:42 INFO Start time:    2019-05-27 14:05:42.792585
2019-05-27  14:05:42 ERROR Failed to complete
Traceback (most recent call last):
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\climate_indices\__main__.py", line 1658, in main
    arguments.netcdf_precip, arguments.var_name_precip
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\climate_indices\__main__.py", line 1524, in _prepare_file
    nco = Nco()
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\nco\nco.py", line 58, in __init__
    self.nco_path = os.path.split(distutils.spawn.find_executable("ncks"))[0]
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Spweedy\Anaconda3\envs\nzclim2\Scripts\process_climate_indices.exe\__main__.py", line 9, in <module>
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\climate_indices\__main__.py", line 1658, in main
    arguments.netcdf_precip, arguments.var_name_precip
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\climate_indices\__main__.py", line 1524, in _prepare_file
    nco = Nco()
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\site-packages\nco\nco.py", line 58, in __init__
    self.nco_path = os.path.split(distutils.spawn.find_executable("ncks"))[0]
  File "c:\users\spweedy\anaconda3\envs\nzclim2\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
**To Reproduce**
My data can be downloaded in google drive;
https://drive.google.com/drive/folders/1VSOKp_xPLaSxOuDrtnI1VUriUyURETHV?usp=sharing

**Expected behavior**
An expected SPI output

**Desktop (please complete the following information):**
- OS: Windows 
- Version: 10

**Comment by monocongo** [comment]
Thanks @wsor330. From what I can tell you are missing the NCO requirement. The following line shows that the Python NCO bindings package is looking for the NCO command `ncks` which is not found:

```
self.nco_path = os.path.split(distutils.spawn.find_executable("ncks"))[0]
```

I'm afraid the documentation is not as clear as it should be in terms of this requirement for NCO to be installed.

My advice is to use the Anaconda virtual environments as described in the documentation since this is the easiest way to install the NCO package. If so then it's as simple as running the following command line in the activated Anaconda virtual environment:

```
$ conda install -c conda-forge nco
```

Otherwise, if you're using a vanilla Python virtual environment or no virtual environment at all then you can install NCO using [the instructions found here](http://nco.sourceforge.net/#Executables).

Once you've installed NCO on your machine try again and let me know how it goes, if you need further help, etc.

BTW I have tested the code with your dataset and I've run into an issue at line 745 of `__main__.py`. Without looking into it further I'd say you are using a time format that I'm not yet accommodating properly. Just a heads up that you may run into this next, and if so please let me know so I can try to work out the problem there. It looks like I'm expecting to get time values as "YYYYMMDD". It's been a while since I've looked at this part of the code so I'm not sure what's going on there, but I feel certain that we can work this out for your use case.

**Comment by wsor330** [comment]
I appreciate the help, @monocongo ! It seems i did get an error at line 745 of ```__main__.py``` , as what you have found.
I  tried changing the time format to what you have described as "YYYYMMDD", but i still get an error that is still related to the time format as below. 
```
line 1073, in _compute_write_index
    keyword_arguments["data_start_year"],
````
So what is the proper time format supposed to be? I assumed that the program counts it, provided that there is no missing date in-between the dataset.
Also looking at one of the cmorph example file, the time format is also not clear, I assumed it is from ```ordinal date time```, but converting it to said format seems to give ```0098-12-31``` as the starting year which seems odd. 
Note; I have updated the file in google drive provided above, to having the date format as described. and added in units for the data, to resolve errors for having void of units.

**Comment by monocongo** [comment]
So it turns out that the data type for time values is `numpy.datetime64`. So, for example, a value looks like this when I evaluate it in the PyCharm debugger: `1895-01-01T00:00:00.000000000`. This is why the code is pulling off the first four digits from the initial time value as the initial data year at line 745.

You can examine the [example input files](https://github.com/monocongo/example_climate_indices/tree/master/example/input) to see how valid input NetCDF files look, maybe that can help you with ideas as to how to put together your own input files so they are easy for this code to process? Also, it may be possible to use [xarray](https://github.com/pydata/xarray) to write your files in a manner that makes them contain valid (i.e. `numpy.datetime64`) time values.

**Comment by monocongo** [comment]
Closing due to inactivity. Please contact me if I can help you with this issue, or feel free to reopen the issue with updates as to your status.

**Comment by Amarounek** [comment]
This works for me!
```
<xarray.Dataset>
Dimensions:             (lat: 115, lon: 140, time: 15157)
Coordinates:
  * lat                 (lat) float64 -7.4 -7.5 -7.6 -7.7 ... -18.6 -18.7 -18.8
  * lon                 (lon) float64 21.1 21.2 21.3 21.4 ... 34.8 34.9 35.0
  * time                (time) datetime64[ns] 1979-01-01 ... 2020-06-30
Data variables:
    Precipitation_Flux  (time, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.9.2 (http://mpimet.mpg.de/...
    history:      Sat Nov 28 18:08:48 2020: ncks -v Precipitation_Flux -d lon...
    Conventions:  CF-1.7
    CDO:          Climate Data Operators version 1.9.2 (http://mpimet.mpg.de/...
    NCO:          netCDF Operators version 4.7.9 (Homepage = http://nco.sf.ne...
```
Use xarray response function like this!

```
import xarray as xr
data = data.transpose("lat", "lon", "time")
```
