### ISSUE TITLE
Error in computing PET f"Invalid latitude value: {latitude_degrees} (must be " +

### ISSUE THREAD

**Issue by mmaoyi** [monocongo/climate_indices#334]
Hi James

I get the message below while I am trying to compute PET.  Please help

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/mmaoyi/miniconda3/bin/process_climate_indices", line 10, in <module>
    sys.exit(main())
  File "/home/mmaoyi/miniconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1718, in main
    kwargs
  File "/home/mmaoyi/miniconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1061, in _compute_write_index
    args=args,
  File "/home/mmaoyi/miniconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1299, in _parallel_process
    pool.map(_apply_along_axis_double, chunk_params)
  File "/home/mmaoyi/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/mmaoyi/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numba.errors.UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'FORMAT_VALUE'

File "../../../../../miniconda3/lib/python3.7/site-packages/climate_indices/indices.py", line 488:
def pet(temperature_celsius: np.ndarray,
    <source elided>
    else:
        message = (f"Invalid latitude value: {latitude_degrees} (must be " +
        ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new

**Comment by monocongo** [comment]
I'm pretty sure this is related to [this issue](https://github.com/numba/numba/issues/3250) which prevents the usage of formatted strings within `numba.jit` annotated functions. It was partially addressed in issue #306 but apparently there are some other formatted strings that need to be replaced with old-fashioned formatted strings in order to work with numba.

**Comment by monocongo** [comment]
OK, @mmaoyi, now please reinstall from the master branch and try again. The recent changes I made in PR #335 should fix this issue for you, if not please let me know.

**Comment by mmaoyi** [comment]
Many thanks James.  I am using the pypi version of the code and applied the fixes to the offending lines. 

Kind regards

**Comment by An1you** [comment]
> OK, @mmaoyi, now please reinstall from the master branch and try again. The recent changes I made in PR #335 should fix this issue for you, if not please let me know.

Hi,James

I get the message below while I am trying to compute PET. Please help

Traceback (most recent call last):
  File "scpdsi_CNRM.py", line 86, in <module>
    pet_his_g6[i,j,:] = indices.pet(temperature_celsius=tas_his_g6[i,j,:],
  File "/public/home/tiancg/mysoft/anaconda3/envs/meteo/lib/python3.8/site-packages/numba/dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/public/home/tiancg/mysoft/anaconda3/envs/meteo/lib/python3.8/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/public/home/tiancg/mysoft/anaconda3/envs/meteo/lib/python3.8/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
[1mUse of unsupported opcode (FORMAT_VALUE) found
[1m
File "../../../../tiancg/mysoft/anaconda3/envs/meteo/lib/python3.8/site-packages/climate_indices/indices.py", line 583:[0m
[1mdef pet(temperature_celsius: np.ndarray,
    <source elided>

[1m    message = (f"Invalid latitude value: {latitude_degrees}" +
[0m    [1m^[0m[0m
[0m
