### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by crestedcaracaryn** [monocongo/climate_indices#400]
It looks as though this was a previous problem awhile back but seems to be unresolved. Below is my input for palmers and the following error code: 

cdross@IGSKLACBLTOWT MINGW64 ~/Desktop/ClimateIndices
$ process_climate_indices --index palmers --periodicity monthly --netcdf_precip C:/Users/cdross/Desktop/ClimateIndices/ClimateData/hist_precip_monthly.nc --var_name_precip precip --netcdf_pet C:/Users/cdross/Desktop/ClimateIndices/ClimateData/hist_pet_monthly.nc --var_name_pet pet --netcdf_awc C:/Users/cdross/Desktop/ClimateIndices/ClimateData/hist_awc_monthly.nc  --var_name_awc awc --output_file_base C:/Users/cdross/Desktop/ClimateIndices/ClimateData/results/palmers --calibration_start_year 2009 --calibration_end_year 2019 --multiprocessing all
2020-10-22  17:49:53 INFO Start time:    2020-10-22 17:49:53.190083
2020-10-22  17:49:53 INFO Computing PALMERS
2020-10-22  17:49:53 ERROR Failed to complete

Traceback (most recent call last):
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 869, in _compute_write_index
    args=args,
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 1279, in _parallel_process
    params["sub_array_end"] = split_indices[i + 1]
IndexError: list index out of range
Traceback (most recent call last):
  File "c:\miniconda3\envs\palmers\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\palmers\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\palmers\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 869, in _compute_write_index
    args=args,
  File "c:\miniconda3\envs\palmers\lib\site-packages\climate_indices\__main__.py", line 1279, in _parallel_process
    params["sub_array_end"] = split_indices[i + 1]
IndexError: list index out of range

**Comment by monocongo** [comment]
It's very unlikely that I'll have time to debug and fix this anytime soon. Have at it, and if you discover a fix then please submit a PR. Thanks in advance!

**Comment by monocongo** [comment]
Thanks a lot for this contribution, @ScottWales , very helpful!
