### ISSUE TITLE
ValueError: Invalid periodicity argument: monthly

### ISSUE THREAD

**Issue by Amarounek** [monocongo/climate_indices#402]
Hello!

I would like to report a bug when I am using IMERG for the calculation of SPI. It seems that periodicity doesn't take monthly as a valid value. I hope that I was using `nco ncks` and `nco ncrcat` rightly.

Here's my command:
```python37 process_grid.py --index spi --periodicity monthly --netcdf_precip ../example_inputs/IMERG_concat_ncpdq.nc4 --var_name_precip precipitation --output_file_base ../results/IMERG --scales 12 --calibration_start_year 2000 --calibration_end_year 2019```

Here is bug report:
```
2020-11-06  14:22:32 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\lukat\OneDrive\Dokumenty\Python kody\climate_indices\scripts\process_grid.py", line 465, in _process_latitude_scaled
    self.periodicity)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "C:\Users\lukat\scoop\apps\python37\current\lib\site-packages\numpy\lib\shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
ValueError: Invalid periodicity argument: monthly
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_grid.py", line 1137, in <module>
    args.scales)
  File "process_grid.py", line 1062, in process_grid
    grid_processor.run()
  File "process_grid.py", line 332, in run
    result.get()
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
ValueError: Invalid periodicity argument: monthly
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\lukat\OneDrive\Dokumenty\Python kody\climate_indices\scripts\process_grid.py", line 465, in _process_latitude_scaled
    self.periodicity)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "C:\Users\lukat\scoop\apps\python37\current\lib\site-packages\numpy\lib\shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
ValueError: Invalid periodicity argument: monthly
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "process_grid.py", line 1137, in <module>
    args.scales)
  File "process_grid.py", line 1062, in process_grid
    grid_processor.run()
  File "process_grid.py", line 332, in run
    result.get()
  File "C:\Users\lukat\scoop\apps\python37\current\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
ValueError: Invalid periodicity argument: monthly
```

**Comment by monocongo** [comment]
Thanks for reporting this, @Amarounek 

Is `process_grid.py` your own script? If not then you may be using an out-of-date version of the package, I think I remember having a script with that name in a previous version but that's just a guess.

Make sure you get the latest version of this package from the master branch or by using `pip install climate-indices` (pip is the best way, IMHO).

If you can post a link to your dataset, or maybe just a small piece of it that also causes this error, then I will try to reproduce your error and debug this.

Also please describe what you did to your dataset with `ncks` and `ncrcat` (most likely this will be in the history section of the NetCDF).

**Comment by Amarounek** [comment]
Oh my... You are right that I am blindly using the tutorial of ARSET about IMERG and not looking at new approaches. You are probably right, the new version will only use the cmd command `$ process_climate_indices` with a python library/packages and not some external code. I will try it later! Thx!

**Comment by monocongo** [comment]
Yes, I became aware of this when several others contacted me with error reports. Every one of these was the result of using a broken, out-of-date version that NCEI is serving on drought.gov. I didn't put that package together so I can't comment as to why it is in error, but the working code is always available here. I notified the authors of that tutorial at NASA of this issue (Feb 2020) and they told me that it would be fixed. So either they didn't update it to point to the correct code repository or you are referring to a tutorial without the update. Maybe you can contact the NASA people and add another voice explaining that there tutorials are useless when they depend on a broken software distribution linked in error? amita.v.mehta@nasa.gov and sean.mccartney@nasa.gov are the contacts at NASA (the original authors of the training materials). Thanks, @Amarounek!

**Comment by Amarounek** [comment]
Okay, I will try it. They are using a new version of the website and it is still not fully developed, so there are no files for tutorials yet. However, I will let them know after the migration of tutorial files to the new website (And if they are not updated). Thank you to for the quick response! 

PS: Is possible to ask you on some issues by email if I would like to explain something about evapotranspiration files? :-)

**Comment by monocongo** [comment]
Yes, I will help if possible.

**Comment by Saumik43** [comment]
Sorry if it sounds stupid, but is there any sample code or any guide regarding how to use the newer version? I am currently at a fix how to calculate the SPI in the new version. Any help would be appreciated.

**Comment by monocongo** [comment]
No problem, check this out for some examples:
https://climate-indices.readthedocs.io/en/latest/#indices-processing

**Comment by bennyistanto** [comment]
@Amarounek you can check [my guideline](https://github.com/wfpidn/SPI) to compute SPI, I have modified some steps that written in the ARSET training manual. Its available for IMERG and CHIRPS data.

**Comment by Amarounek** [comment]
Seems promising! Thank you! I will try to use your tutorial with Agrometeorological indicators from Copernicus! However, I am still struggling with NCO little bit as I am quite new in this field of study (Crop growth modelling is my native). 

Thanks! 

Sorry for a little offtopic. I will comment it under your bennyistanto project thereafter...
