### ISSUE TITLE
Value error in SPEI calculation - please help with the format of the input data

### ISSUE THREAD

**Issue by coderkhaleesi** [monocongo/climate_indices#411]
**Describe the bug**

For calculation of SPEI, I am getting this error.
The value of "time" variable is not clear. That is why I think I am getting an error like this. Could I please get the format of the netCDF files to be used as input?

(climate) root@vultr:/home/climate-index# process_climate_indices --index spei --periodicity monthly --netcdf_precip data/Precip_2010_2019_monthly.nc --var_name_precip  precip --netcdf_temp data/Temp_2010_2019_monthly.nc --var_name_temp temp --output_file_base output/spei_2010_2019_monthly --scales 1 2 --calibration_start_year 2010 --calibration_end_year 2019 --multiprocessing all

2021-01-09  02:21:08 INFO Start time:    2021-01-09 02:21:08.514938
2021-01-09  02:21:08 INFO Computing PET
1.0
2021-01-09  02:21:08 ERROR Failed to complete
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1714, in main
    kwargs
  File "/root/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 741, in _compute_write_index
    data_start_year = int(str(dataset["time"].values[0])[0:4])
ValueError: invalid literal for int() with base 10: '1.0'
Traceback (most recent call last):
  File "/root/anaconda3/bin/process_climate_indices", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1714, in main
    kwargs
  File "/root/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 741, in _compute_write_index
    data_start_year = int(str(dataset["time"].values[0])[0:4])
ValueError: invalid literal for int() with base 10: '1.0'

**To Reproduce**
process_climate_indices --index spei --periodicity monthly --netcdf_precip data/Precip_2010_2019_monthly.nc --var_name_precip  precip --netcdf_temp data/Temp_2010_2019_monthly.nc --var_name_temp temp --output_file_base output/spei_2010_2019_monthly --scales 1 2 --calibration_start_year 2010 --calibration_end_year 2019 --multiprocessing all

**Expected behavior**
It should output a netCDF file

**Screenshots**

**Desktop (please complete the following information):**
- OS: \[e.g. iOS] Debian
- Version: \[e.g. 22] 10

**Additional context**

**Comment by monocongo** [comment]
Yes, the time values should be of the form "\<units\> since \<timestamp\>" as described [here](https://www.unidata.ucar.edu/software/netcdf/time/recs.html). Off the top of my head I think we can use anything that xarray supports when utilizing this driver script since it leverages xarray for handling the time coordinate variable. There are utility functions to handle this situation for monthly data, for example you can use [this function](https://github.com/monocongo/climate_indices/blob/4d3a04d4290ad3738999ac1c4de8a31ad5c1d938/src/climate_indices/utils.py#L97) to help you compute an array of values to use for monthly data.

I can look into this further if the above isn't enough to get you over the hump, just let me know.

**Comment by fipoucat** [comment]
Wonder if you solved your problem? I am doing a test with spei but getting an error about time too.
Here is my error:
2021-05-02  15:06:13 INFO Start time:    2021-05-02 15:06:13.668052
2021-05-02  15:06:15 INFO Computing PET
2021-05-02  15:06:15 ERROR Failed to complete
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/__main__.py", line 1712, in main
    arguments.netcdf_pet, arguments.var_name_pet = _compute_write_index(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/__main__.py", line 769, in _compute_write_index
    temp_unit = dataset[temp_var_name].units.lower()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xarray/core/common.py", line 232, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/process_climate_indices", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/__main__.py", line 1712, in main
    arguments.netcdf_pet, arguments.var_name_pet = _compute_write_index(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/__main__.py", line 769, in _compute_write_index
    temp_unit = dataset[temp_var_name].units.lower()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xarray/core/common.py", line 232, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
my data time variable:

variables:
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:bounds = "time_bnds" ;
		time:units = "minutes since 1979-01-01 12:00" ;
		time:calendar = "standard" ;
		time:axis = "T" ;
	double time_bnds(time, bnds) ;
