### ISSUE TITLE
SPI - latitude and longigute

### ISSUE THREAD

**Issue by ValescaFernandes** [monocongo/climate_indices#412]
Hello, I'm trying to run the script, but my data has the variables latitude and longitude instead of lat and lon. Could you tell me where I can change in the _main_.py script to be able to use my data? Or if there is any suggestion for me to change my data with the variables from latitude to lat, and longitude to lon. Thanks.

**Comment by Amarounek** [comment]
Hello Valesca!

Are you a Python user? A quite easy way is to use xarray library for changes inside a NetCDF file... I recommend it to you!

**Comment by monocongo** [comment]
Yes, you can update the [\_\_main\_\_.py](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L378) script and replace the variable name from "lat" to "latitude", etc. This gives me a good idea to add these as options or at least hard-coded as a single variable, i.e. _VAR_NAME_LON ="lon" in order to make it easy to change in one place rather than this find/replace approach we need to use now.

Besides using xarray I can also recommend [NCO](https://github.com/nco/nco) if you want to use a command line tool for manipulating NetCDF files.

There are plans to better document the data format requirements, as this kind of thing is not obvious to many users.

**Comment by ValescaFernandes** [comment]
Yes, I did the trocar test everything that was latitude for lat and everything that is longitude for lon. And still giving the same error:

ValueError: Invalid precipitation variable dimensions: ('time', 'latitude', 'longitude')
Valid dimension names and order: [('lat', 'lon', 'tempo'), ('tempo', 'lat', 'lon'), ('tempo', 'division'), ('division' , 'Time')]

for the nco I tried giving the command: ncrename -v latitude, lat -v longitude, lon -d latitude, lat -d longitude, lon notarnc output.nc

 however for some reason, when I try to plot the data after giving this command above, the data does not open in any program.

The idea of ​​changing the name in the program itself would be better, but in which more programs do I have to change in addition to the main.py which is found in src / Climate_indices

**Comment by ValescaFernandes** [comment]
I managed to change the script. but now this error is:

(indices_env) LOCAL \ valesca.fernandes@linux237: ~ / Documents / Forecast / SPI $ process_climate_indices --index spi --periodicity monthly --netcdf_prec dado_mm.nc --var_name_precip precip --output_file_base spi --scales 3 6 --calibrear_start 3 6 1998 --calibration_end_year 2018
2021-01-25 16:05:39 INFO Start time: 2021-01-25 16: 05: 39.419149
Error in calling operator ncpdq with:
>>> /home/valesca.fernandes/anaconda3/envs/indices_env/bin/ncpdq -a latitude, longitude, time -O --output = / tmp / ncpdq_dado_mm.nco0wt7pbr.tmp dado_mm.nc <<<
Inputs: dado_mm.nc
B''
2021-01-25 16:06:08 ERROR Failed to complete
Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1664, in main
    netcdf_precip = _prepare_file (arguments.netcdf_precip,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1533, in _prepare_file
    netcdf_file = nco.ncpdq (input = netcdf_file,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/nco/nco.py", line 342, in get
    raise NCOException (** retvals)
nco.nco.NCOException: (returncode: -9) b ''
Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/bin/process_climate_indices", line 8, in <module>
    sys.exit (main ())
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1664, in main
    netcdf_precip = _prepare_file (arguments.netcdf_precip,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1533, in _prepare_file
    netcdf_file = nco.ncpdq (input = netcdf_file,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/nco/nco.py", line 342, in get
    raise NCOException (** retvals)
nco.nco.NCOException: (returncode: -9) b ''

**Comment by monocongo** [comment]
It may be that you changed the name of the variables but not the corresponding dimensions? 

The thing is you've hit the part of the code where it uses NCO to re-orient the data into (lat, lon, time), so that the time dimension is inner-most. This calls the NCO command `ncpdq` and that's the command which is croaking. It looks like it doesn't like the NetCDF file for some reason, but the error message is cryptic at best. 

Many of the issues I deal with are involved with the section where NCO is used to re-orient the dataset (often on Windows) so this is not surprising. I should maybe just document the data format requirements and let users do the data preprocessing on their own rather than having it cooked into the code as it is, since that seems to cause so many errors for users. NCO uses a lot of low-level libraries to do its thing, there's a lot of C and Fortran magic involved, and it's tricky to install sometimes, especially on Windows. Based on what I see above it doesn't seem you're running on Windows -- can you confirm? Almost always it works out that the issue is around how we're using or installing NCO (user error), as it's very mature/solid software, so let's focus on that at first. If your file is corrupted then NCO is likely to also croak like this when running the commands at command line, so please try that to confirm validity of the NetCDF file.

Another thing to try is to change both the dimensions and corresponding coordinate variables to (lat, lon, time) and put them into that order before using the file as input for the climate indices processing script. If you do this then there should be no reason for the `nco.ncpdq` command to be called, so we're essentially bypassing NCO at that point, at least within this package's code. 

I recommend also asking about this on the [NCO Help Forum](https://sourceforge.net/p/nco/discussion/9830/), @czender et al may be able to set you right. And maybe post a link to your data if possible so I can try this myself (no guarantee that I can do that quickly though).

**Comment by czender** [comment]
Is the dataset in netCDF4 format? If so, the `ncrename` issue mentioned above has all the hallmarks of being due to a longstanding netCDF bug discussed here: https://github.com/Unidata/netcdf-c/issues/597
`ncpdq` itself has no known issues, whether with netCDF3 or netCDF4. However, the PyNCO wrapper to `ncpdq` may have issues. If you suspect that is the case, then please submit a small reproducible example of the problem to the help forum mentioned above.

**Comment by ValescaFernandes** [comment]
so I use linux to run, and would you have an email that can forward the data? because the data is very heavy, I don't know if I can carry it around here.

and in relation to giving the command ncpdq -a lat, lon, time .. I did the test and he does not finish, he kills before finishing.

**Comment by ValescaFernandes** [comment]
# #

**Comment by ValescaFernandes** [comment]
I forwarded my data to the email monocongo@gmail.com

**Comment by ValescaFernandes** [comment]
now the question I'm thinking is why I put together two different databases. most of the series is CHIRPS and the last data is a corrected CFS model data.

**Comment by monocongo** [comment]
I used a single `ncrename` command to rename the coordinate variables and associated dimensions from "longitude" to "lon" and "latitude" to "lat":

`$ ncrename -d longitude,lon -d latitude,lat -v longitude,lon -v latitude,lat ~/Downloads/dado_mm.nc dado_mm_renamed.nc`

After this completed I was able to use the resulting NetCDF as valid input for the indices processing with no errors.

However, when I attempt to plot the files using Panoply all of them give errors around non-unique (multiple zero) axis values. This is happening for the renamed input NetCDF as well as the resulting SPI file. This may be related to the known bug Charlie referenced above, I need to look into this further...

**Comment by ValescaFernandes** [comment]
I moved the dice again, and it opens in panoply, but now it gives a new error:

(indices_env) LOCAL \ valesca.fernandes@linux237: ~ / Documents / Forecast / SPI $ process_climate_indices --index spi --periodicity monthly --netcdf_prec teste02.nc --var_name_precip precip --output_file_base spi --scales 3 6 --calibrear_start_ 6 2000 --calibration_end_year 2018
2021-01-27 11:40:51 INFO Start time: 2021-01-27 11: 40: 51.091110
2021-01-27 11:41:15 INFO Computing 3-month SPI / Gamma
2021-01-27 11:41:23 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback:
"" "
Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func (* args, ** kwds))
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list (map (* args))
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1335, in _apply_alongitudeg_axis
    computed_array = np.apply_alongitudeg_axis (func1d,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
    raise AttributeError ("module {! r} has no attribute"
AttributeError: module 'numpy' has no attribute 'apply_alongitudeg_axis'
"" "

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1684, in main
    _compute_write_index (kwrgs)
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1011, in _compute_write_index
    _parallel_process (keyword_arguments ["index"],
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1298, in _parallel_process
    pool.map (_apply_alongitudeg_axis, chunk_params)
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async (func, iterable, mapstar, chunksize) .get ()
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'apply_alongitudeg_axis'
multiprocessing.pool.RemoteTraceback:
"" "
Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func (* args, ** kwds))
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list (map (* args))
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1335, in _apply_alongitudeg_axis
    computed_array = np.apply_alongitudeg_axis (func1d,
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
    raise AttributeError ("module {! r} has no attribute"
AttributeError: module 'numpy' has no attribute 'apply_alongitudeg_axis'
"" "

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/bin/process_climate_indices", line 8, in <module>
    sys.exit (main ())
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1684, in main
    _compute_write_index (kwrgs)
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1011, in _compute_write_index
    _parallel_process (keyword_arguments ["index"],
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/site-packages/climate_indices/__main__.py", line 1298, in _parallel_process
    pool.map (_apply_alongitudeg_axis, chunk_params)
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async (func, iterable, mapstar, chunksize) .get ()
  File "/home/valesca.fernandes/anaconda3/envs/indices_env/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'apply_alongitudeg_axis'

**Comment by monocongo** [comment]
Are you sure you're using the latest version from PyPI? I ask because I see error messages from `main.py` which no longer exists in the current package (much of it was refactored into `__main__.py`). Try recreating your conda environment and install this package from the latest version in PyPI. You shouldn't be doing anything other than creating and activating the environment, then run `pip install climate-indices`. At that point you should be good to go.

Simple recipe:
```
$ conda create -n newenv python=3.7
$ conda activate newenv 
$ pip install climate-indices
$ process_climate_indices --index spi ...
```

**Comment by bennyistanto** [comment]
> Yes, I did the trocar test everything that was latitude for lat and everything that is longitude for lon. And still giving the same error:
> 
> ValueError: Invalid precipitation variable dimensions: ('time', 'latitude', 'longitude')
> Valid dimension names and order: [('lat', 'lon', 'tempo'), ('tempo', 'lat', 'lon'), ('tempo', 'division'), ('division' , 'Time')]
> 
> for the nco I tried giving the command: ncrename -v latitude, lat -v longitude, lon -d latitude, lat -d longitude, lon notarnc output.nc
> 
> however for some reason, when I try to plot the data after giving this command above, the data does not open in any program.
> 
> The idea of ​​changing the name in the program itself would be better, but in which more programs do I have to change in addition to the main.py which is found in src / Climate_indices

Hi @ValescaFernandes few month ago, I also experience similar problem when I try to use CHIRTS temperature data to calculate PET. Successful rename using ncrename, but failed when open using Panoply.

It solved based on suggestion from @monocongo to use xarray. And as @Amarounek said above, here's the code and feel free to adjust:

```python
import pandas as pd
import xarray as xr

ds = xr.open_dataset("/path/input.nc",
        decode_times=False)
units, reference_date = ds.time.attrs['units'].split('since')
ds['time'] = pd.date_range(start=reference_date, periods=ds.sizes['time'], freq='MS')
ds["Tmax"].attrs["units"] = "degrees_celsius"
name_dict = {
    "latitude": "lat",
    "longitude": "lon",
}
ds = ds.rename(name_dict=name_dict)
ds.to_netcdf(path="/path/output.nc")
```

**Comment by monocongo** [comment]
Closing due to inactivity. Please re-open if the issue persists.

**Comment by naomitoledor** [comment]
> Are you sure you're using the latest version from PyPI? I ask because I see error messages from `main.py` which no longer exists in the current package (much of it was refactored into `__main__.py`). Try recreating your conda environment and install this package from the latest version in PyPI. You shouldn't be doing anything other than creating and activating the environment, then run `pip install climate-indices`. At that point you should be good to go.
> 
> Simple recipe:
> 
> ```
> $ conda create -n newenv python=3.7
> $ conda activate newenv 
> $ pip install climate-indices
> $ process_climate_indices --index spi ...
> ```

Hi, I have a similar problem, but default conda pipeline does not have python 3.7 version available for osx-arm64 architecture: This is the error:   File "/Users/naomitoledo/anaconda3/envs/climate_indices/lib/python3.8/site-packages/climate_indices/__spi__.py", line 800, in build_dataset_spi_grid
    da_spi = xr.DataArray(
  File "/Users/naomitoledo/anaconda3/envs/climate_indices/lib/python3.8/site-packages/xarray/core/dataarray.py", line 408, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/Users/naomitoledo/anaconda3/envs/climate_indices/lib/python3.8/site-packages/xarray/core/dataarray.py", line 157, in _infer_coords_and_dims
    raise ValueError(
ValueError: conflicting sizes for dimension 'lat': length 192 on the data but length 1000 on coordinate 'lat'. 


this is my dataset: <xarray.Dataset>
Dimensions:        (lat: 1000, lon: 3200, time: 192)
Coordinates:
  * lat            (lat) float32 -49.95 -49.85 -49.75 ... 49.75 49.85 49.95
  * lon            (lon) float32 -159.9 -159.9 -159.8 ... 159.8 159.9 159.9
  * time           (time) datetime64[ns] 2004-01-01 2004-02-01 ... 2019-12-01
Data variables:
    precipitation  (time, lat, lon) float32 ...
Attributes:
    CDI:                                    Climate Data Interface version 1....
    Conventions:                            CF-1.6
    Original_Producer_Metadata_FileHeader:  DOI=10.5067/GPM/IMERG/3B-MONTH/06...
    Original_Producer_Metadata_FileInfo:    DataFormatVersion=6a;\nTKCodeBuil...
    Original_Producer_Metadata_GridHeader:  BinMethod=ARITHMETIC_MEAN;\nRegis...
    InputPointer:                           3B-MO.MS.MRG.3IMERG.20040101-S000...
    history_L34RS:                          'Created by L34RS v1.4.4 @ NASA G...
    CDO:                                    Climate Data Operators version 1....
    NCO:                                    netCDF Operators version 5.2.4 (H...
    history:                                Mon Jun 17 10:49:49 2024: ncatted...
