### ISSUE TITLE
DataArry error

### ISSUE THREAD

**Issue by fipoucat** [monocongo/climate_indices#429]
I am doing a test with spei but getting an error about time too.
Here is my error:
2021-05-02 15:06:13 INFO Start time: 2021-05-02 15:06:13.668052
2021-05-02 15:06:15 INFO Computing PET
2021-05-02 15:06:15 ERROR Failed to complete
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/main.py", line 1712, in main
arguments.netcdf_pet, arguments.var_name_pet = _compute_write_index(
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/main.py", line 769, in _compute_write_index
temp_unit = dataset[temp_var_name].units.lower()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xarray/core/common.py", line 232, in getattr
raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/bin/process_climate_indices", line 8, in
sys.exit(main())
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/main.py", line 1712, in main
arguments.netcdf_pet, arguments.var_name_pet = _compute_write_index(
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/main.py", line 769, in _compute_write_index
temp_unit = dataset[temp_var_name].units.lower()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xarray/core/common.py", line 232, in getattr
raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
my data time variable:

variables:
double time(time) ;
time:standard_name = "time" ;
time:long_name = "Time" ;
time:bounds = "time_bnds" ;
time:units = "minutes since 1979-01-01 12:00" ;
time:calendar = "standard" ;
time:axis = "T" ;
double time_bnds(time, bnds) ;

A sample of my time axis:
data:

 time = 21600, 64080, 106560, 150480, 194400, 238320, 282240, 326880, 370800, 
    414720, 458640, 502560, 547200, 590400, 633600, 677520, 721440, 765360, 
    809280, 853920, 897840, 941760, 985680, 1029600, 1074240, 1116720, 
    1159200, 1203120, 1247040, 1290960, 1334880, 1379520, 1423440, 1467360, 
    1511280, 1555200, 1599840, 1642320, 1684800, 1728720, 1772640, 1816560, 
    1860480, 1905120, 1949040, 1992960, 2036880, 2080800, 2125440, 2167920, 

I am stuck because of this and need help to solve it.

**Comment by monocongo** [comment]
The final error message attempts to dial you in:

**AttributeError: 'DataArray' object has no attribute 'units'**

It's not complaining about the `time` variable but instead the temperature variable. Looking a little further up in the stack trace we see the cause:
```
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/climate_indices/main.py", line 769, in _compute_write_index
temp_unit = dataset[temp_var_name].units.lower()
```
So what's happening is that our code is reading the temperature variable's `units` attribute, but it doesn't exist.

Can we confirm that this is indeed what's going on? Please list the temperature variable like you've done for the time variable above, so we can see if it does or does not contain a `units` attribute. If it does then the mystery continues...

**Comment by fipoucat** [comment]
This what I have for temperature:

variables:
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:long_name = "Longitude" ;
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:long_name = "Latitude" ;
	double time(time) ;
		time:long_name = "Time" ;
		time:units = "minutes since 1979-01-01 12:00" ;
	double tas(time, lat, lon) ;
		tas:_FillValue = -999000000. ;
data:

 lon = -18, -17.75, -17.5, -17.25, -17, -16.75, -16.5, -16.25, -16, -15.75, 
    -15.5, -15.25, -15, -14.75, -14.5, -14.25, -14, -13.75, -13.5, -13.25, 
    -13, -12.75, -12.5, -12.25, -12, -11.75, -11.5, -11.25, -11, -10.75, 
    -10.5, -10.25, -10, -9.75, -9.5, -9.25, -9, -8.75, -8.5, -8.25, -8, 
    -7.75, -7.5, -7.25, -7, -6.75, -6.5, -6.25, -6 ;

 lat = 10.25, 10.5, 10.75, 11, 11.25, 11.5, 11.75, 12, 12.25, 12.5, 12.75, 
    13, 13.25, 13.5, 13.75, 14, 14.25, 14.5, 14.75, 15, 15.25, 15.5, 15.75, 
    16, 16.25, 16.5, 16.75, 17, 17.25, 17.5, 17.75, 18, 18.25, 18.5, 18.75, 
    19, 19.25 ;

 time = 0, 1440, 2880, 4320, 5760, 7200, 8640, 10080, 11520, 12960, 14400, 
    15840, 17280, 18720, 20160, 21600, 23040, 24480, 25920, 27360, 28800, 
    30240, 31680, 33120, 34560, 36000, 37440, 38880, 40320, 41760, 43200, 
    44640, 46080, 47520, 48960, 50400, 51840, 53280, 54720, 56160, 57600, 
    59040, 60480, 61920, 63360, 64800, 66240, 67680, 69120, 70560, 72000, 
    73440, 74880, 76320, 77760, 79200, 80640, 82080, 83520, 84960, 86400, 
    87840, 89280, 90720, 92160, 93600, 95040, 96480, 97920, 99360, 100800, 
    102240, 103680, 105120, 106560, 108000, 109440, 110880, 112320, 113760, 
    115200, 116640, 118080, 119520, 120960, 122400, 123840, 125280, 126720,

**Comment by fipoucat** [comment]
Sorry, below the correct file:

dimensions:
	time = UNLIMITED ; // (456 currently)
	bnds = 2 ;
	lon = 49 ;
	lat = 37 ;
variables:
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:bounds = "time_bnds" ;
		time:units = "minutes since 1979-01-01 12:00" ;
		time:calendar = "standard" ;
		time:axis = "T" ;
	double time_bnds(time, bnds) ;
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "Longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "Latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	double tas(time, lat, lon) ;
		tas:_FillValue = -999000000. ;
		tas:missing_value = -999000000. ;
		tas:cell_methods = "time: mean" ;

// global attributes:
		:CDI = "Climate Data Interface version 1.9.10 (https://mpimet.mpg.de/cdi)" ;
		:Conventions = "CF-1.6" ;
		:frequency = "mon" ;
		:history = "Sun May 02 13:53:48 2021: cdo monmean sen_tas_025_cera79-16.nc sem_mm_tas_cerA_79-16" ;
		:CDO = "Climate Data Operators version 1.9.10 (https://mpimet.mpg.de/cdo)" ;
data:

 time = 21600, 64080, 106560, 150480, 194400, 238320, 282240, 326880, 370800, 
    414720, 458640, 502560, 547200, 590400, 633600, 677520, 721440, 765360, 
    809280, 853920, 897840, 941760, 985680, 1029600, 1074240, 1116720, 
    1159200, 1203120, 1247040, 1290960, 1334880, 1379520, 1423440, 1467360, 
    1511280, 1555200, 1599840, 1642320, 1684800, 1728720, 1772640, 1816560, 
    1860480, 1905120, 1949040, 1992960, 2036880, 2080800, 2125440, 2167920, 
    2210400, 2254320, 2298240, 2342160, 2386080, 2430720, 2474640, 2518560, 
    2562480, 2606400, 2651040, 2694240, 2737440, 2781360, 2825280, 2869200, 
    2913120, 2957760, 3001680, 3045600, 3089520, 3133440, 3178080, 3220560, 
    3263040, 3306960, 3350880, 3394800, 3438720, 3483360, 3527280, 3571200, 
    3615120, 3659040, 3703680, 3746160, 3788640, 3832560, 3876480, 3920400,

**Comment by monocongo** [comment]
OK this is good, it tells us some things.

This shows we are in fact missing a `units` attribute on the `tas` (temperature) variable:
```
double tas(time, lat, lon) ;
tas:_FillValue = -999000000. ;
tas:missing_value = -999000000. ;
tas:cell_methods = "time: mean" ;
```
So add an appropriate `units` attribute to this variable and let's see if that fixes things for you. You'll want to use one of the values specified [here](https://github.com/monocongo/climate_indices/blob/master/src/climate_indices/__main__.py#L765), so if you're using another unit then you'll need to convert your data into one of the supported units.

**Comment by monocongo** [comment]
I'm closing this issue due to inactivity. Feel free to re-open if the issue isn't resolved.
