### ISSUE TITLE
Palmer index crashes in terminal with error link to Numba

### ISSUE THREAD

**Issue by Linimie** [monocongo/climate_indices#433]
**Describe the bug**
When running the palmer index in the terminal the action is in error and aborts due to a `with` statement in palmer.py. Calculating PET, SPI or SPEI is not influenced by this error. I have first [raised this error ](https://github.com/numba/numba/issues/7091#issuecomment-856871706)with the Numba people but was informed that `with `driven context manager use is very limited in Numba. The issues lies within the palmer code, using a statement that cannot be used in the terminal. Is there a solution for this issue?

**To Reproduce**
1. download and install the climate_indices
2. download the example data
3. run palmer on example data with given code in documentation: `process_climate_indices --index palmers --periodicity monthly --netcdf_precip nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base ../output/nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all`

**Expected behavior**
The expected behaviour is to produce the palmer nc files in the output folder.

**Screenshots**
See error code below message

**Desktop (please complete the following information):**
- Ubuntu 20.04.2 LTS
- Python 3.7
- Mumba 0.53.1

**Additional context**
Error code:

2021-06-09  09:41:49 INFO Start time:    2021-06-09 09:41:49.368028
2021-06-09  09:41:49 INFO Computing PALMERS
2021-06-09  09:42:08 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/pylowering.py", line 168, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1478, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1142, in _palmers
    calibration_end_year=parameters["calibration_end_year"])
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 439, in _compile_for_args
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 372, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 120, in run_pass
    lowered = backend_object_mode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 118, in backend_object_mode
    state.flags)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 78, in _py_lowering_stage
    lower.lower()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

During: lowering "enter_with $phi102.0" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 869, in _compute_write_index
    args=args,
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1296, in _parallel_process
    pool.map(_apply_along_axis_palmers, chunk_params)
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numba.core.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

During: lowering "enter_with $phi102.0" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/pylowering.py", line 168, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1478, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1142, in _palmers
    calibration_end_year=parameters["calibration_end_year"])
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 439, in _compile_for_args
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 372, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 120, in run_pass
    lowered = backend_object_mode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 118, in backend_object_mode
    state.flags)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 78, in _py_lowering_stage
    lower.lower()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

During: lowering "enter_with $phi102.0" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linda/anaconda3/bin/process_climate_indices", line 10, in <module>
    sys.exit(main())
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 869, in _compute_write_index
    args=args,
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1296, in _parallel_process
    pool.map(_apply_along_axis_palmers, chunk_params)
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numba.core.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7f1ba023c850>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

During: lowering "enter_with $phi102.0" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)

**Comment by monocongo** [comment]
You may have better results by disabling numba. Set the `NUMBA_DISABLE_JIT` environment variable in the bash shell before running the indices processing command. For example:
```
$ export NUMBA_DISABLE_JIT=1
```
In any event I'm not very confident about the Palmer indices provided in this package, and I don't advise using the PDSI etc. for any serious research, unless you're focusing on this implementation itself and can help validate the results and/or improve the code quality. All other indices provided in this package are rock solid and are still being used by NOAA.
