### ISSUE TITLE
ValueError: the first argument to .drop_sel must be a dictionary"

### ISSUE THREAD

**Issue by mjh1366** [monocongo/climate_indices#495]
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

I'm using the PyPi version of climate indices with input datasets in climate-indices' package: nclimgrid_lowres_prcp.nc

 I'm getting this  Error" raise ValueError(f"the first argument to .{func_name} must be a dictionary") ValueError: the first argument to .drop_sel must be a dictionary" 

**Describe the bug**

```
    **raise ValueError(f"the first argument to .{func_name} must be a dictionary")
ValueError: the first argument to .drop_sel must be a dictionary**
```

**To Reproduce**

```
1. conda create -n indices_env
2. activate indices_env
3. pip install climate-indices
4. pip install -r requirements.txt
5. pip-compile -o requirements.txt pyproject.toml
6. conda install -c conda-forge nco
7. pip install netcdf4
8. pip install h5netcdf
```
9. `(env1) E:\climate\climate_indices-master\input>process_climate_indices --index spi --periodicity monthly --netcdf_precip ./nclimgrid_lowres_prcp.nc --var_name_precip prcp --output_file_base ../output/nclimgrid_lowres --scales 6 12 --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all`
```
2023-01-10  19:53:33 INFO Start time:    2023-01-10 19:53:33.396280
2023-01-10  19:53:33 INFO Computing 6-month SPI/Pearson
2023-01-10  19:53:33 ERROR Failed to complete
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 1708, in main
    _compute_write_index(kwrgs)
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 809, in _compute_write_index
    _drop_data_into_shared_arrays_grid(dataset,
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 637, in _drop_data_into_shared_arrays_grid
    dataset = dataset.drop_sel(var_name)
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\dataset.py", line 4486, in drop_sel
    labels = either_dict_or_kwargs(labels, labels_kwargs, "drop_sel")
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\utils.py", line 286, in either_dict_or_kwargs
    raise ValueError(f"the first argument to .{func_name} must be a dictionary")
ValueError: the first argument to .drop_sel must be a dictionary
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 1708, in main
    _compute_write_index(kwrgs)
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 809, in _compute_write_index
    _drop_data_into_shared_arrays_grid(dataset,
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 637, in _drop_data_into_shared_arrays_grid
    dataset = dataset.drop_sel(var_name)
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\dataset.py", line 4486, in drop_sel
    labels = either_dict_or_kwargs(labels, labels_kwargs, "drop_sel")
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\utils.py", line 286, in either_dict_or_kwargs
    **raise ValueError(f"the first argument to .{func_name} must be a dictionary")
ValueError: the first argument to .drop_sel must be a dictionary**
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- win-64
- 10

**Additional context**

**Comment by monocongo** [comment]
Thanks for the reminder about this @mjh1366 

This was fixed in #493 but the version on PyPI is out-of-date, so we will rectify this by resolving #489.

In the meantime, you can instead install this package from the master branch which should be OK again.

**Comment by monocongo** [comment]
A new version is available now via PyPI, please advise if you still have this or any other issues with the latest version there. Thanks!

**Comment by mjh1366** [comment]
Thanks for your consideration. Now If I use input datasets in climate-indices' package, there will be no problem:

```
(env3) E:\climate2\climate_indices-master>process_climate_indices --index spi --periodicity monthly --netcdf_precip ./nclimgrid_lowres_prcp1.nc --var_name_precip prcp --output_file_base ./nclimgrid_lowres --scales 6 12 --calibration_start_year 1982 --calibration_end_year 1997 --multiprocessing all
2023-01-13  19:00:45 INFO Start time:    2023-01-13 19:00:45.683248
2023-01-13  19:00:46 INFO Computing 6-month SPI/Pearson
2023-01-13  19:01:56 INFO Computing 6-month SPI/Gamma
2023-01-13  19:03:25 INFO Computing 12-month SPI/Pearson
2023-01-13  19:04:49 INFO Computing 12-month SPI/Gamma
2023-01-13  19:05:17 INFO End time:      2023-01-13 19:05:17.267028
2023-01-13  19:05:17 INFO Elapsed time:  0:04:31.583780
```

But if I use my input datasets, the same problem will occur:

```
(env3) E:\climate2\climate_indices-master>process_climate_indices --index spi --periodicity monthly --netcdf_precip ./nclimgrid_lowres_prcp.nc --var_name_precip precip --output_file_base ./nclimgrid_lowres --scales 6 12 --calibration_start_year 1982 --calibration_end_year 1997 --multiprocessing all
2023-01-13  18:58:22 INFO Start time:    2023-01-13 18:58:22.469086
2023-01-13  18:58:22 INFO Computing 6-month SPI/Pearson
2023-01-13  18:58:22 ERROR Failed to complete
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 1715, in main
    _compute_write_index(kwrgs)
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 752, in _compute_write_index
    dataset = dataset.drop_sel(var)
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\dataset.py", line 4486, in drop_sel
    labels = either_dict_or_kwargs(labels, labels_kwargs, "drop_sel")
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\utils.py", line 286, in either_dict_or_kwargs
    raise ValueError(f"the first argument to .{func_name} must be a dictionary")
ValueError: the first argument to .drop_sel must be a dictionary
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 1715, in main
    _compute_write_index(kwrgs)
  File "C:\Program Files\Python310\lib\site-packages\climate_indices\__main__.py", line 752, in _compute_write_index
    dataset = dataset.drop_sel(var)
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\dataset.py", line 4486, in drop_sel
    labels = either_dict_or_kwargs(labels, labels_kwargs, "drop_sel")
  File "C:\Program Files\Python310\lib\site-packages\xarray\core\utils.py", line 286, in either_dict_or_kwargs
    raise ValueError(f"the first argument to .{func_name} must be a dictionary")
ValueError: the first argument to .drop_sel must be a dictionary
```


I upload my input datasets here:

Monthly precipitation data from CORDEX SouthAsia- model remoo2009
File format : NetCDF
Cell size (x,y)= 0.5,0.5
GCS_WGS_1984
Parameter name=precip
Grid coordinates :            
lon : 43.25 to 63.75 by 0.5 degrees_east
lat : 24.25 to 40.75 by 0.5 degrees_north
[New WinRAR ZIP archive.zip](https://github.com/monocongo/climate_indices/files/10413394/New.WinRAR.ZIP.archive.zip)

**Comment by monocongo** [comment]
This results from the file being written by CDO which defaults to using the time dimension as the outermost for the data variables. This package's processing script expects variables with dims = (lat, lon, time) instead. This used to be performed in the script itself but NCO is buggy on Windows and many users reported issues, so we recently removed that from this script. We need to document this better to make users aware that they need to re-orient the data variables to (lat, lon, time) otherwise this will happen. Also BTW, the file you are using does not have units for the precip variable, which also causes an error.

This removal of NCO support should cause a new version since this breaks things for some users. Thanks for bringing this to my attention, @mjh1366

**Comment by monocongo** [comment]
BTW I misspoke above, the order is off in that file but that wasn't the bug. xarray.Dataset.drop_sel() takes a list and instead the code drops a single variable at a time. I have a fix ready for PR soon, stay tuned...

**Comment by mjh1366** [comment]
Thank you so much.
I can prepare my data for this package. I use NCO and re-orient the data variable to (lat,lon,time). as well as I define units for precip variable. 

```
ncpdq -O -a lat,lon,time nclimgrid_lowres_prcp.nc nclimgrid_lowres_prcp2.nc
ncwa -a bnds ncpdq nclimgrid_lowres_prcp2.nc nclimgrid_lowres_prcp3.nc
ncks -C -x -v time_bnds nclimgrid_lowres_prcp3.nc nclimgrid_lowres_prcp4.nc
ncatted -O -a name,precip,c,c,precip nclimgrid_lowres_prcp4.nc nclimgrid_lowres_prcp5.nc
ncatted -O -a unite,precip,c,c,millimeter nclimgrid_lowres_prcp5.nc nclimgrid_lowres_prcp6.nc
```
Thanks for your consideration, @monocongo

**Comment by Mahsabzg** [comment]
I received the same error. I checked the structure of my data, it looks correct. I appreciate if you could help me. 
```
ncdump -h data.nc
dimensions:
	lat = 240 ;
	lon = 280 ;
	time = 3652 ;
variables:
	double lat(lat) ;
		lat:standard_name = "grid_latitude" ;
		lat:long_name = "latitude in rotated pole grid" ;
		lat:units = "degrees" ;
		lat:axis = "Y" ;
	double lon(lon) ;
		lon:standard_name = "grid_longitude" ;
		lon:long_name = "longitude in rotated pole grid" ;
		lon:units = "degrees" ;
		lon:axis = "X" ;
	float precipitation(lat, lon, time) ;
		precipitation:long_name = "precipitation amount" ;
		precipitation:units = "mm" ;
		precipitation:table = 1 ;
		precipitation:grid_mapping = "rotated_pole" ;
		precipitation:_FillValue = -9999.f ;
		precipitation:missing_value = -9999.f ;
		precipitation:cell_methods = "height: mean" ;
	char rotated_pole ;
		rotated_pole:grid_mapping_name = "rotated_latitude_longitude" ;
		rotated_pole:grid_north_pole_latitude = 49.5 ;
		rotated_pole:grid_north_pole_longitude = -186. ;
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time variable" ;
		time:units = "days since 2010-01-01 06:00:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
```

**Comment by monocongo** [comment]
Please post a link to your data @Mahsabzg 
I'm overwhelmed at my day job right now so no time to work on this in the near term, but if someone else has the time then they'll need a copy of your data just like I will to diagnose and fix the issue.
Please make sure you're using the latest code installed from PyPI or the master branch. PR #505 may have fixed this error.

**Comment by Mahsabzg** [comment]
Thank you for your immediate answer. I installed it with: 
```
conda create -n indices_env
activate indices_env
pip install climate-indices
conda install -c conda-forge netcdf4 h5netcdf
```
I upload my input dataset.
[first_row.zip](https://github.com/monocongo/climate_indices/files/15331126/first_row.zip)

**Comment by Mahsabzg** [comment]
I also upload my original data and and how to  prepare it.  
[data.zip](https://github.com/monocongo/climate_indices/files/15344954/data.zip)

```
cdo mergetime *.nc merge.nc
ncwa -a height
ncks -C -x -v lat
ncks -C -x -v lon
cdo chname,rlat,lat
cdo chname,rlon,lon
ncatted -a units,precipitation,modify,c,'mm'

## bash file 
ncpdq -a lat,lon,time -O 
ncks -A -v lat 
ncks -A -v lon 
ncks -A -v time 
ncks -A -v rotated_pole 
ncks -A -v precipitation 

ncks -O --fix_rec_dmn lat

ncdump -h
```

**Comment by keyao22** [comment]
When I applied this to a global scale, the latitude range excluded -90 and 90 degrees.

**Comment by monocongo** [comment]
@keyao22 How the math works for some of the indices precludes the usage of the top/bottom limits, i.e. 90/-90 degrees throws the calculations into infinity etc. Another example is that the Thornthwaite PET can't be computed above or below 60 degrees lat.

**Comment by davidadzavon** [comment]
Hello,

Can someone please help me solve this error?

**Here's my code**

` process_climate_indices --index pet --periodicity monthly --netcdf_temp ./merged_tp_min_max_t2m_lat_lon_time.nc --var_name_temp t2m --output_file_base ./ERA5_all_one --calibration_start_year 1980 --calibration_end_year 2024 --multiprocessing all`

**Here's the error**
`ValueError: the first argument to .drop_sel must be a dictionary`


ncdump -h merged_tp_min_max_t2m_lat_lon_time.nc
netcdf merged_tp_min_max_t2m_lat_lon_time {
dimensions:
        lat = 321 ;
        lon = 341 ;
        time = 540 ;
variables:
        double lat(lat) ;
                lat:_FillValue = NaN ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
        double lon(lon) ;
                lon:_FillValue = NaN ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
        double time(time) ;
                time:_FillValue = NaN ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:units = "seconds since 1970-01-01" ;
                time:calendar = "proleptic_gregorian" ;
        float tp(time, lat, lon) ;
                tp:_FillValue = NaNf ;
                tp:standard_name = "unknown" ;
                tp:long_name = "Total precipitation" ;
                tp:units = "mm" ;
                tp:GRIB_paramId = 228 ;
                tp:GRIB_dataType = "fc" ;
                tp:GRIB_numberOfPoints = 109461 ;
                tp:GRIB_typeOfLevel = "surface" ;
                tp:GRIB_stepUnits = 1 ;
                tp:GRIB_stepType = "accum" ;
                tp:GRIB_gridType = "regular_ll" ;
                tp:GRIB_uvRelativeToGrid = 0 ;
                tp:GRIB_NV = 0 ;
                tp:GRIB_Nx = 341 ;
                tp:GRIB_Ny = 321 ;
                tp:GRIB_cfName = "unknown" ;
                tp:GRIB_cfVarName = "tp" ;
                tp:GRIB_gridDefinitionDescription = "Latitude/Longitude Grid" ;
                tp:GRIB_iDirectionIncrementInDegrees = 0.25 ;
                tp:GRIB_iScansNegatively = 0 ;
                tp:GRIB_jDirectionIncrementInDegrees = 0.25 ;
                tp:GRIB_jPointsAreConsecutive = 0 ;
                tp:GRIB_jScansPositively = 0 ;
                tp:GRIB_latitudeOfFirstGridPointInDegrees = 40. ;
                tp:GRIB_latitudeOfLastGridPointInDegrees = -40. ;
                tp:GRIB_longitudeOfFirstGridPointInDegrees = -30. ;
                tp:GRIB_longitudeOfLastGridPointInDegrees = 55. ;
                tp:GRIB_missingValue = 3.40282346638529e+38 ;
                tp:GRIB_name = "Total precipitation" ;
                tp:GRIB_shortName = "tp" ;
                tp:GRIB_totalNumber = 0 ;
                tp:GRIB_units = "m" ;
                tp:GRIB_surface = 0. ;
                tp:missing_value = NaNf ;
        float mx2t(time, lat, lon) ;
                mx2t:_FillValue = NaNf ;
                mx2t:standard_name = "unknown" ;
                mx2t:long_name = "Maximum temperature at 2 metres since previous post-processing" ;
                string mx2t:units = "°C" ;
                mx2t:GRIB_paramId = 201 ;
                mx2t:GRIB_dataType = "fc" ;
                mx2t:GRIB_numberOfPoints = 109461 ;
                mx2t:GRIB_typeOfLevel = "surface" ;
                mx2t:GRIB_stepUnits = 1 ;
                mx2t:GRIB_stepType = "max" ;
                mx2t:GRIB_gridType = "regular_ll" ;
                mx2t:GRIB_uvRelativeToGrid = 0 ;
                mx2t:GRIB_NV = 0 ;
                mx2t:GRIB_Nx = 341 ;
                mx2t:GRIB_Ny = 321 ;
                mx2t:GRIB_cfName = "unknown" ;
                mx2t:GRIB_cfVarName = "mx2t" ;
                mx2t:GRIB_gridDefinitionDescription = "Latitude/Longitude Grid" ;
                mx2t:GRIB_iDirectionIncrementInDegrees = 0.25 ;
                mx2t:GRIB_iScansNegatively = 0 ;
                mx2t:GRIB_jDirectionIncrementInDegrees = 0.25 ;
                mx2t:GRIB_jPointsAreConsecutive = 0 ;
                mx2t:GRIB_jScansPositively = 0 ;
                mx2t:GRIB_latitudeOfFirstGridPointInDegrees = 40. ;
                mx2t:GRIB_latitudeOfLastGridPointInDegrees = -40. ;
                mx2t:GRIB_longitudeOfFirstGridPointInDegrees = -30. ;
                mx2t:GRIB_longitudeOfLastGridPointInDegrees = 55. ;
                mx2t:GRIB_missingValue = 3.40282346638529e+38 ;
                mx2t:GRIB_name = "Maximum temperature at 2 metres since previous post-processing" ;
                mx2t:GRIB_shortName = "mx2t" ;
                mx2t:GRIB_totalNumber = 0 ;
                mx2t:GRIB_units = "K" ;
                mx2t:GRIB_surface = 0. ;
                mx2t:missing_value = NaNf ;
        float mn2t(time, lat, lon) ;
                mn2t:_FillValue = NaNf ;
                mn2t:standard_name = "unknown" ;
                mn2t:long_name = "Minimum temperature at 2 metres since previous post-processing" ;
                string mn2t:units = "°C" ;
                mn2t:GRIB_paramId = 202 ;
                mn2t:GRIB_dataType = "fc" ;
                mn2t:GRIB_numberOfPoints = 109461 ;
                mn2t:GRIB_typeOfLevel = "surface" ;
                mn2t:GRIB_stepUnits = 1 ;
                mn2t:GRIB_stepType = "max" ;
                mn2t:GRIB_gridType = "regular_ll" ;
                mn2t:GRIB_uvRelativeToGrid = 0 ;
                mn2t:GRIB_NV = 0 ;
                mn2t:GRIB_Nx = 341 ;
                mn2t:GRIB_Ny = 321 ;
                mn2t:GRIB_cfName = "unknown" ;
                mn2t:GRIB_cfVarName = "mn2t" ;
                mn2t:GRIB_gridDefinitionDescription = "Latitude/Longitude Grid" ;
                mn2t:GRIB_iDirectionIncrementInDegrees = 0.25 ;
                mn2t:GRIB_iScansNegatively = 0 ;
                mn2t:GRIB_jDirectionIncrementInDegrees = 0.25 ;
                mn2t:GRIB_jPointsAreConsecutive = 0 ;
                mn2t:GRIB_jScansPositively = 0 ;
                mn2t:GRIB_latitudeOfFirstGridPointInDegrees = 40. ;
                mn2t:GRIB_latitudeOfLastGridPointInDegrees = -40. ;
                mn2t:GRIB_longitudeOfFirstGridPointInDegrees = -30. ;
                mn2t:GRIB_longitudeOfLastGridPointInDegrees = 55. ;
                mn2t:GRIB_missingValue = 3.40282346638529e+38 ;
                mn2t:GRIB_name = "Minimum temperature at 2 metres since previous post-processing" ;
                mn2t:GRIB_shortName = "mn2t" ;
                mn2t:GRIB_totalNumber = 0 ;
                mn2t:GRIB_units = "K" ;
                mn2t:GRIB_surface = 0. ;
                mn2t:missing_value = NaNf ;
        float t2m(time, lat, lon) ;
                t2m:_FillValue = NaNf ;
                t2m:standard_name = "unknown" ;
                t2m:long_name = "2 metre temperature" ;
                t2m:units = "K" ;
                t2m:GRIB_paramId = 167 ;
                t2m:GRIB_dataType = "an" ;
                t2m:GRIB_numberOfPoints = 109461 ;
                t2m:GRIB_typeOfLevel = "surface" ;
                t2m:GRIB_stepUnits = 1 ;
                t2m:GRIB_stepType = "instant" ;
                t2m:GRIB_gridType = "regular_ll" ;
                t2m:GRIB_uvRelativeToGrid = 0 ;
                t2m:GRIB_NV = 0 ;
                t2m:GRIB_Nx = 341 ;
                t2m:GRIB_Ny = 321 ;
                t2m:GRIB_cfName = "unknown" ;
                t2m:GRIB_cfVarName = "t2m" ;
                t2m:GRIB_gridDefinitionDescription = "Latitude/Longitude Grid" ;
                t2m:GRIB_iDirectionIncrementInDegrees = 0.25 ;
                t2m:GRIB_iScansNegatively = 0 ;
                t2m:GRIB_jDirectionIncrementInDegrees = 0.25 ;
                t2m:GRIB_jPointsAreConsecutive = 0 ;
                t2m:GRIB_jScansPositively = 0 ;
                t2m:GRIB_latitudeOfFirstGridPointInDegrees = 40. ;
                t2m:GRIB_latitudeOfLastGridPointInDegrees = -40. ;
                t2m:GRIB_longitudeOfFirstGridPointInDegrees = -30. ;
                t2m:GRIB_longitudeOfLastGridPointInDegrees = 55. ;
                t2m:GRIB_missingValue = 3.40282346638529e+38 ;
                t2m:GRIB_name = "2 metre temperature" ;
                t2m:GRIB_shortName = "2t" ;
                t2m:GRIB_totalNumber = 0 ;
                t2m:GRIB_units = "K" ;
                t2m:GRIB_surface = 0. ;
                t2m:missing_value = NaNf ;
