### ISSUE TITLE
error in calling ncpdq

### ISSUE THREAD

**Issue by wewe-sst** [monocongo/climate_indices#509]
2023-04-20  14:04:39 INFO Start time:    2023-04-20 14:04:39.307828
Error in calling operator ncpdq with:
>>> D:\cygwin\bin\ncpdq -a lat,lon,time -O --output=D:\cygwin\tmp\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp Mon_ZYH_SMCI_500m_2001_2020_10cm.nc <<<
Inputs: Mon_ZYH_SMCI_500m_2001_2020_10cm.nc
b"/bin/mv: cannot move 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp.pid1128.ncpdq.tmp' to 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp': Device or resource busy\n"
2023-04-20  14:05:51 ERROR Failed to complete
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1669, in main
    arguments.var_name_precip)
  File "d:\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1537, in _prepare_file
    options=[f'-a "{dims}"', "-O"])
  File "d:\anaconda3\lib\site-packages\nco\nco.py", line 342, in get
    raise NCOException(**retvals)
nco.nco.NCOException: (returncode:1) b"/bin/mv: cannot move 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp.pid1128.ncpdq.tmp' to 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp': Device or resource busy\n"
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1669, in main
    arguments.var_name_precip)
  File "d:\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1537, in _prepare_file
    options=[f'-a "{dims}"', "-O"])
  File "d:\anaconda3\lib\site-packages\nco\nco.py", line 342, in get
    raise NCOException(**retvals)
nco.nco.NCOException: (returncode:1) b"/bin/mv: cannot move 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp.pid1128.ncpdq.tmp' to 'D:\\cygwin\\tmp\\ncpdq_Mon_ZYH_SMCI_500m_2001_2020_10cm.nc840840xf.tmp': Device or resource busy\n"

**Comment by monocongo** [comment]
The latest master branch version should have no dependency on NCO for exactly this reason -- Windows users frequently have issues. My advice is to first properly re-orient and shape your data and then feed it into the `climate_indices` processing script once that's done. You need the dims to be named (`lat`, `lon`, `time`), preferably in that order, and use NaN as missing/fill values.

BTW which version of the code are you using? Did you pull it from the master branch here (maybe via git clone) or instead from PyPI? I think there is still a discrepancy between the PyPI version and the latest master branch, on my list of things to fix...
