### ISSUE TITLE
'DataArray' object has no attribute 'units'

### ISSUE THREAD

**Issue by HEXU-123** [monocongo/climate_indices#542]
Hi:
When I run the the process climate indices it shows me an error about 【'DataArray' object has no attribute 'units'】
**Input code**
process_climate_indices --index spi  --periodicity monthly --netcdf_precip ./rain.nc --var_name_precip pre --output_file_base ./123/cmorph_lowres_daily_conus --scales 3 --calibration_start_year 1961 --calibration_end_year 2021 --multiprocessing all
**Traceback (most recent call last):**
  File "D:\Anaconda3\envs\easy\lib\site-packages\climate_indices\__main__.py", line 1617, in main
    _compute_write_index(kwrgs)
  File "D:\Anaconda3\envs\easy\lib\site-packages\climate_indices\__main__.py", line 753, in _compute_write_index
    precip_unit = dataset[precip_var_name].units.lower()
  File "D:\Anaconda3\envs\easy\lib\site-packages\xarray\core\common.py", line 278, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'
**Traceback (most recent call last):**
File "D:\Anaconda3\envs\easy\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\easy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\easy\Scripts\process_climate_indices.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\envs\easy\lib\site-packages\climate_indices\__main__.py", line 1617, in main
    _compute_write_index(kwrgs)
  File "D:\Anaconda3\envs\easy\lib\site-packages\climate_indices\__main__.py", line 753, in _compute_write_index
    precip_unit = dataset[precip_var_name].units.lower()
  File "D:\Anaconda3\envs\easy\lib\site-packages\xarray\core\common.py", line 278, in __getattr__
    raise AttributeError(
AttributeError: 'DataArray' object has no attribute 'units'

**Comment by bennyistanto** [comment]
Seems your `rain.nc` doesn't have units attribute. You can add it using [NCO](https://nco.sourceforge.net/) command, see below:

```
ncatted -a units,pre,o,c,mm rain.nc
```

`pre` is your variable name
`o` specifies that the attribute should be overwritten if it already exists, or created if it does not exist.
`c` indicates that the type of the attribute is character/string.

Ref: https://linux.die.net/man/1/ncatted

**Comment by monocongo** [comment]
Thanks for bringing this up @HEXU-123, the error message is not very helpful, another for the to-do list

Thank you @bennyistanto for accurately describing the problem of the missing `units` attribute, I need to amend the exception message to highlight that this is required and how the user can fix it (in case they don't stumble onto this issue comments thread to see the NCO command above)
