### ISSUE TITLE
Missing import in grid processing script

### ISSUE THREAD

**Issue by monocongo** [monocongo/climate_indices#70]
The utils module is missing from the imports in process_grid.py.

**Comment by monocongo** [comment]
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/home/james.adams/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/james.adams/anaconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "scripts/process/process_grid.py", line 473, in _process_latitude_palmer
>     if utils.is_data_valid(precip_time_series) and \
> NameError: name 'utils' is not defined
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "scripts/process/process_grid.py", line 774, in <module>
>     args.calibration_end_year)
>   File "scripts/process/process_grid.py", line 702, in process_grid
>     grid_processor.run()
>   File "scripts/process/process_grid.py", line 316, in run
>     result.get()
>   File "/home/james.adams/anaconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
>     raise self._value
> NameError: name 'utils' is not defined
>

**Comment by monocongo** [comment]
math module is missing as well...

**Comment by monocongo** [comment]
all import issues appear to now be resolved
